name: Build and Release Extension

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your preferred Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the extension
      - name: Build the extension
        run: npm run build

      # Zip the build output
      - name: Zip the extension
        run: |
          cd dist
          zip -r ../extension.zip .

      # Upload the ZIP as an artifact
      - name: Upload the dist folder
        uses: actions/upload-artifact@v4.4.3
        with:
          name: dist
          path: dist

        # Generate a date-based tag name
      - name: Generate date-based tag name
        id: generate_tag
        run: |
          # Get the current date and time to ensure unique tags
          TIMESTAMP=$(date +'%Y-%m-%d-%H%M%S')  # Format: YYYY-MM-DD-HHMMSS
          TAG_NAME="release-${TIMESTAMP}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        
      # List dist directory contents again to verify the ZIP exists before release
      - name: List dist directory contents for release
        run: ls -l

        # Create a release using softprops/action-gh-release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.0
        with:
          files: '*.zip'
          tag_name: ${{ env.TAG_NAME }}
          prerelease: ${{ github.ref == 'refs/heads/develop' }}  # Mark as prerelease if on the develop branch
  
